language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -e .[tests]
    - python setup.py compile_catalog
script:
    - py.test
    - ./tests/runonce.sh
    - python setup.py egg_info -bdev sdist --formats gztar
